language: php

php:
  - 7.0
  - 7.1

before_install:
  - travis_retry composer self-update

install:
  - chmod 777 install.sh
  - ./install.sh -q -k -e .env.example
  - travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit